# Generated by Django 5.2.7 on 2025-10-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='departement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROFESSEUR', 'Professeur'), ('ADMIN', 'Administrateur'), ('ETUDIANT', 'Étudiant')], default='PROFESSEUR', max_length=20),
        ),
    ]
