# Generated by Django 5.2.7 on 2025-10-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('coefficient', models.FloatField(default=1.0)),
                ('semestre', models.IntegerField()),
            ],
        ),
    ]
