# Generated by Django 6.0.2 on 2026-02-26 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('coefficient', models.FloatField(default=1.0)),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('etudiants', models.ManyToManyField(blank=True, related_name='modules_inscrits', to='etudiants.etudiant')),
                ('professeurs', models.ManyToManyField(blank=True, related_name='modules', to='utilisateurs.professeur')),
            ],
        ),
    ]
