# Generated by Django 6.0.3 on 2026-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='modules', to='etudiants.promotion'),
        ),
    ]
