# Generated by Django 6.0.2 on 2026-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='etudiants',
            field=models.ManyToManyField(blank=True, related_name='modules', to='utilisateurs.etudiant'),
        ),
        migrations.AddField(
            model_name='module',
            name='professeurs',
            field=models.ManyToManyField(blank=True, related_name='modules', to='utilisateurs.professeur'),
        ),
    ]
