# Generated by Django 5.2.7 on 2025-10-21 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_initial'),
        ('etudiants', '0002_alter_etudiant_email_alter_etudiant_groupe_and_more'),
        ('utilisateurs', '0002_alter_administrateur_departement_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='utilisateurs.professeur'),
        ),
        migrations.AlterField(
            model_name='module',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='etudiants.promotion'),
        ),
    ]
