# Generated by Django 6.0.2 on 2026-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_initial'),
        ('etudiants', '0003_alter_etudiant_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='etudiants',
            field=models.ManyToManyField(blank=True, related_name='modules_inscrits', to='etudiants.etudiant'),
        ),
    ]
