# Generated by Django 6.0.2 on 2026-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='id',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(default='22307556', max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
