# Generated by Django 6.0.2 on 2026-02-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_remove_etudiant_id_etudiant_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True),
        ),
    ]
